import {
  Baby,
  Banknote,
  Book,
  Briefcase,
  Building2,
  Bus,
  Car,
  ChartCandlestick,
  Coffee,
  Coins,
  CreditCard,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Home,
  Landmark,
  Music,
  Package,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Tag,
  TrendingUp,
  User,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { resolveIconName, type IconName } from './names';

/**
 * Name to component. Imported explicitly rather than looked up dynamically so
 * the bundler only ships the icons this app actually uses.
 */
const REGISTRY: Record<IconName, LucideIcon> = {
  utensils: Utensils,
  coffee: Coffee,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  home: Home,
  zap: Zap,
  wifi: Wifi,
  phone: Phone,
  pill: Pill,
  'heart-pulse': HeartPulse,
  dumbbell: Dumbbell,
  users: Users,
  user: User,
  baby: Baby,
  'graduation-cap': GraduationCap,
  'paw-print': PawPrint,
  gift: Gift,
  plane: Plane,
  film: Film,
  'gamepad-2': Gamepad2,
  music: Music,
  book: Book,
  repeat: Repeat,
  briefcase: Briefcase,
  wrench: Wrench,
  scissors: Scissors,
  'heart-handshake': HeartHandshake,
  receipt: Receipt,
  tag: Tag,
  package: Package,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'trending-up': TrendingUp,
  'chart-candlestick': ChartCandlestick,
  coins: Coins,
  'building-2': Building2,
  banknote: Banknote,
  'credit-card': CreditCard,
  smartphone: Smartphone,
  wallet: Wallet,
};

export function iconFor(name: unknown, fallback?: IconName): LucideIcon {
  return REGISTRY[resolveIconName(name, fallback)];
}
